### ISSUE TITLE
Trained Model / Checkpoints of Gun Detection

### ISSUE THREAD

**Issue by NaeemKhan333** [quangnhat185/Machine_learning_projects#3]
@quangnhat185 Thanks for your nice work.Can you provide the trained model or checkpoints for the gun detection project.

**Comment by quangnhat185** [comment]
You can find my pre-trained weight [here](https://drive.google.com/drive/folders/1ub9A46AyRMU1781gsaMUmhP1EhI3ffTt).  Now it was pre-trained weight with 900 epochs but I am going to improve it more soon
