### ISSUE TITLE
"yolo3_custom_test.cfg" how to create this file

### ISSUE THREAD

**Issue by vicky-nike** [quangnhat185/Machine_learning_projects#4]
I successfully trained the weights on my custom dataset after referring your tutorial on Gun Detection. And then I was trying to use these weight to predict the images 
![2020-06-02 19_17_14-Machine_learning_projects_Yolov3_Gun_Detection ipynb at master · quangnhat185_Ma](https://user-images.githubusercontent.com/40816229/83527662-9ac8db80-a4d7-11ea-8612-14768ca44e4f.png)

When i execute this
![2020-06-02 19_20_58-Machine_learning_projects_Yolov3_Gun_Detection ipynb at master · quangnhat185_Ma](https://user-images.githubusercontent.com/40816229/83528049-28a4c680-a4d8-11ea-93d3-e857a95ff3f8.png)

I get error that:
_Failed to parse NetParameter file: darknet/cfg/yolov3_custom_test.cfg in function 'readNetFromDarknet'_

I think its because there is no such file in the directory. Because when I used "yolov3.cfg" and "yolov3.weights" its working fine. 
So how to create that file?

And Thanks for the tutorial, it helped me a lot.

**Comment by quangnhat185** [comment]
Hello @vicky-nike, you can refer `yolov3_custom_test.cfg` from [this link](https://github.com/quangnhat185/Machine_learning_projects/blob/master/Gun_detection_Yolov3/yolov3_custom_test.cfg). This file is just a slightly modifed version of `yolov3.cfg` to work with 1 class detection

**Comment by vicky-nike** [comment]
Thanks a lot @quangnhat185.

**Comment by OMKARTT** [comment]
yolov3_custom_train.cfg and yolov3_custom_test.cfg are same file or any difference?
as I am training on 4 classes

**Comment by quangnhat185** [comment]
Hi @OMKARTT , two of them are differrent. One is used for training and the other for deploying

**Comment by OMKARTT** [comment]
thanks, @quangnhat185  actually I am trained network for 4 classes so can you please tell me where to do changes to generate .cfg file for test
Thank you for your tutorial it helped me a lot

**Comment by HHIR** [comment]
@OMKARTT  Hi dear, 
did you solve it?

**Comment by vicky-nike** [comment]
@HHIR watch this video https://www.youtube.com/watch?v=10joRJt39Ns

**Comment by OMKARTT** [comment]
@HHIR I used same .cfg file which I used for training and it worked finely
